---  
spring: 
  profiles: 
    active:
    - dev

---  
server:
  port: 8201  

spring:
  profiles: dev #开发模式
  application: 
       name: springcloud-config-spring-dev-client
       
eureka:
  client: 
    service-url: 
       defaultZone:  http://eureka7001.com:7001/eureka/       


